In [1]:
import numpy as np
import pandas as pd

In [2]:
df1 = pd.read_csv('covid_19_india.csv')
df2 = pd.read_csv('StatewiseTestingDetails.csv')

In [6]:
df1.head(10)
df2.head(10)

         Date                        State  TotalSamples Negative  Positive
0  2020-04-17  Andaman and Nicobar Islands        1403.0     1210      12.0
1  2020-04-24  Andaman and Nicobar Islands        2679.0      NaN      27.0
2  2020-04-27  Andaman and Nicobar Islands        2848.0      NaN      33.0
3  2020-05-01  Andaman and Nicobar Islands        3754.0      NaN      33.0
4  2020-05-16  Andaman and Nicobar Islands        6677.0      NaN      33.0
5  2020-05-19  Andaman and Nicobar Islands        6965.0      NaN      33.0
6  2020-05-20  Andaman and Nicobar Islands        7082.0      NaN      33.0
7  2020-05-21  Andaman and Nicobar Islands        7167.0      NaN      33.0
8  2020-05-22  Andaman and Nicobar Islands        7263.0      NaN      33.0
9  2020-05-23  Andaman and Nicobar Islands        7327.0      NaN      33.0

In [8]:
df1.info()
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 18110 entries, 0 to 18109
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Sno                       18110 non-null  int64
 1   Date                      18110 non-null  str
 2   Time                      18110 non-null  str
 3   State/UnionTerritory      18110 non-null  str
 4   ConfirmedIndianNational   18110 non-null  str
 5   ConfirmedForeignNational  18110 non-null  str
 6   Cured                     18110 non-null  int64
 7   Deaths                    18110 non-null  int64
 8   Confirmed                 18110 non-null  int64
dtypes: int64(4), str(5)
memory usage: 1.2 MB
<class 'pandas.DataFrame'>
RangeIndex: 16336 entries, 0 to 16335
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date          16336 non-null  str
 1   State         16336 non-null  str
 2   TotalSamples  16336 non-null  float64
 3   Negative      6969 non-null   str
 4   Positive      5662 non-null   float64
dtypes: float64(2), str(3)
memory usage: 638.3 KB

In [10]:
df1.rename(columns={"State/UnionTerritory": "State"}, inplace=True)
df1.head()

,Sno,Date,Time,State,ConfirmedIndianNational,ConfirmedForeignNational,Cured,Deaths,Confirmed
0,1,2020-01-30,6:00 PM,Kerala,1,0,0,0,1
1,2,2020-01-31,6:00 PM,Kerala,1,0,0,0,1
2,3,2020-02-01,6:00 PM,Kerala,2,0,0,0,2
3,4,2020-02-02,6:00 PM,Kerala,3,0,0,0,3
4,5,2020-02-03,6:00 PM,Kerala,3,0,0,0,3

In [11]:
duplicate_list = pd.merge(df1, df2)
unique_list= duplicate_list['State'].unique().tolist()
len(unique_list)

36