In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Pokemon.csv')
df.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

In [20]:
df[df["Name"]=='Jolteon'].head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
146,135,Jolteon,Electric,NaN,525,65,65,60,110,95,130,1,False

In [17]:
jolteon_df = df[df["Name"]=="Jolteon"]
print('---- Jolteon DataFrame ---')
print(jolteon_df[["Name", "Type 1", "Attack", "Sp. Atk", "Defense", "Sp. Def"]])

---- Jolteon DataFrame ---
        Name    Type 1  Attack  Sp. Atk  Defense  Sp. Def
146  Jolteon  Electric      65      110       60       95

In [25]:
df_type = df[df["Type 1"] == "Ground"]

In [26]:
df_type_gen1 = df_type[df_type['Generation']==1]

In [27]:
df_type_gen1_sorted = df_type_gen1.sort_values('Sp. Def')

In [28]:
best_defender = df_type_gen1_sorted.tail(1)

print("\n--- Best Gen 1 Ground-Type Counter ---")
print(best_defender[['Name', 'Type 1', 'Generation', 'Sp. Def', 'HP']])

--- Best Gen 1 Ground-Type Counter ---
        Name  Type 1  Generation  Sp. Def  HP
113  Marowak  Ground           1       80  60